'use client'
import { useActionState } from 'react'
import { PROJECT_CATEGORIES, type Project } from '@/features/projects/types'
import { uploadProjectMedia, type ProjectActionState } from '@/features/projects/actions'
import { MediaUploadField } from './media-upload-field'
const initial:ProjectActionState={ok:true,message:''}
type Action=(state:ProjectActionState,data:FormData)=>Promise<ProjectActionState>
const input='rounded-xl border border-white/12 bg-white/[.035] px-4 py-3 text-white outline-none placeholder:text-white/25'
export function ProjectForm({project,action}:{project?:Project;action:Action}){const [state,formAction,pending]=useActionState(action,initial);const error=(key:string)=>state.fieldErrors?.[key]?.[0];return <form action={formAction} className="grid gap-6"><div className="grid gap-4 md:grid-cols-2"><Field label="Title" error={error('title')}><input className={input} name="title" required defaultValue={project?.title}/></Field><Field label="Slug" error={error('slug')}><input className={input} name="slug" required defaultValue={project?.slug}/></Field><Field label="Category" error={error('category')}><select className={input} name="category" defaultValue={project?.category??'Video Editing'}>{PROJECT_CATEGORIES.map(c=><option className="bg-neutral-950" key={c}>{c}</option>)}</select></Field><Field label="Year" error={error('year')}><input className={input} name="year" type="number" min="2000" max="2100" defaultValue={project?.year??new Date().getFullYear()}/></Field><Field label="Client (optional)" error={error('clientName')}><input className={input} name="clientName" defaultValue={project?.clientName??''}/></Field><Field label="Sort order" error={error('sortOrder')}><input className={input} name="sortOrder" type="number" min="0" defaultValue={project?.sortOrder??0}/></Field></div><Field label="Description" error={error('description')}><textarea className={`${input} min-h-32`} name="description" maxLength={1000} defaultValue={project?.description}/></Field><div className="grid gap-4 md:grid-cols-2">{([['Thumbnail URL','thumbnailUrl',project?.thumbnailUrl],['Video URL','videoUrl',project?.videoUrl],['Instagram URL','instagramUrl',project?.instagramUrl],['External project URL','externalUrl',project?.externalUrl]] as const).map(([label,name,value])=><Field key={name} label={label} error={error(name)}><input className={input} name={name} type="url" defaultValue={value??''} placeholder="https://…"/></Field>)}</div>{project&&<div className="grid gap-4 md:grid-cols-2"><MediaUploadField label="Upload thumbnail" kind="image" currentUrl={project.thumbnailUrl} action={uploadProjectMedia.bind(null,project.id,'image')}/><MediaUploadField label="Upload preview video" kind="video" currentUrl={project.videoUrl} action={uploadProjectMedia.bind(null,project.id,'video')}/></div>}<div className="flex flex-wrap gap-5"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isFeatured" defaultChecked={project?.isFeatured}/> Featured</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isPublished" defaultChecked={project?.isPublished}/> Published</label></div>{state.message&&<p role="status" className={state.ok?'text-sm text-emerald-300':'text-sm text-red-300'}>{state.message}</p>}<button disabled={pending} className="w-fit rounded-xl bg-white px-5 py-3 font-semibold text-black disabled:opacity-50">{pending?'Saving…':'Save project'}</button></form>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm text-white/55"><span>{label}</span>{children}{error&&<span className="text-xs text-red-300">{error}</span>}</label>}
