'use server'
import { revalidatePath } from 'next/cache'
import { requireAdmin } from '@/lib/auth/admin'
import { createClient } from '@/lib/supabase/server'
import { SITE_SETTINGS_ID } from '@/lib/site-defaults'
import { siteSettingsSchema } from './schema'
export type SettingsActionState={ok:boolean;message:string;fieldErrors?:Record<string,string[]>}
const fail=(message:string,fieldErrors?:Record<string,string[]>):SettingsActionState=>({ok:false,message,fieldErrors})
export async function updateSiteSettings(_:SettingsActionState,fd:FormData):Promise<SettingsActionState>{await requireAdmin();const obj=Object.fromEntries(['fullName','headline','heroSupportingText','heroVideoUrl','heroPosterUrl','profileImageUrl','bio','instagramUrl','whatsappNumber','email','primaryCtaLabel','primaryCtaTarget','secondaryCtaLabel','secondaryCtaTarget'].map(k=>[k,String(fd.get(k)??'')]));const p=siteSettingsSchema.safeParse(obj);if(!p.success)return fail('Please fix the highlighted fields.',p.error.flatten().fieldErrors as Record<string,string[]>);const v=p.data,s=await createClient();const {error}=await s.from('site_settings').update({full_name:v.fullName,headline:v.headline,hero_supporting_text:v.heroSupportingText,bio:v.bio,instagram_url:v.instagramUrl,whatsapp_number:v.whatsappNumber,email:v.email,primary_cta_label:v.primaryCtaLabel,primary_cta_target:v.primaryCtaTarget,secondary_cta_label:v.secondaryCtaLabel,secondary_cta_target:v.secondaryCtaTarget}).eq('id',SITE_SETTINGS_ID);if(error)return fail(error.message);revalidatePath('/');revalidatePath('/admin/settings');return{ok:true,message:'Settings saved.'}}
export async function uploadSiteMedia(field:'heroVideo'|'heroPoster'|'profileImage',fd:FormData):Promise<SettingsActionState>{const admin=await requireAdmin();const file=fd.get('file');if(!(file instanceof File)||file.size===0)return fail('Choose a file first.');const config={heroVideo:{column:'hero_video_url',kind:'video' as const},heroPoster:{column:'hero_poster_url',kind:'image' as const},profileImage:{column:'profile_image_url',kind:'image' as const}}[field];const s=await createClient();const {data,error}=await s.from('site_settings').select(config.column).eq('id',SITE_SETTINGS_ID).single();if(error)return fail(error.message);const {replaceMedia,managedPathFromPublicUrl}=await import('@/features/media/service');const old=(data as Record<string,string>|null)?.[config.column]??'';const bucket=config.kind==='image'?'portfolio-images':'portfolio-videos';const r=await replaceMedia({kind:config.kind,file,ownerId:admin.userId,storage:s.storage as never,previousManagedPath:managedPathFromPublicUrl(old,bucket),persistUrl:async(url)=>{const {error:e}=await s.from('site_settings').update({[config.column]:url}).eq('id',SITE_SETTINGS_ID);return e?{ok:false,message:e.message}:{ok:true}}});if(!r.ok)return fail(r.message);revalidatePath('/');revalidatePath('/admin/settings');return{ok:true,message:r.warning??'Media uploaded.'}}
